# Site settings
title: blarg.co.uk
tagline: technologically astronomical blarg based musings
email: pete@blarg.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blarg.co.uk" # the base hostname & protocol for your site
twitter_username: wrakky
github_username:  wrakky
disqus_name: blargcouk
excerpt_separator: <!--break-->

paginate: 5
paginate_path: "/blog/page-:num"

# Build settings
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

exclude:
  - node_modules
  - package.json
  - gulpfile.js

include:
  - .nojekyll

keep_files:
  - assets